FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runtime
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src

COPy ./Common/Common.Domain /src/Common/Common.Domain
COPY ./Common/Communication /src/Common/Communication
COPY ./EmailProcessor /src/EmailProcessor

WORKDIR /src/EmailProcessor/EmailProcessor.Tests
RUN dotnet restore "EmailProcessor.Tests.csproj" --disable-parallel
RUN dotnet test

WORKDIR /src/EmailProcessor/EmailProcessor.Worker

RUN dotnet restore "EmailProcessor.Worker.csproj" --disable-parallel
RUN dotnet publish "EmailProcessor.Worker.csproj" -c Release -o /app

FROM runtime AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "EmailProcessor.Worker.dll"]